### ISSUE TITLE
ImportError: No module named 'sandbox.rocky.tf.algos.maml_trpo'

### ISSUE THREAD

**Issue by dragen1860** [cbfinn/maml_rl#4]
Here is my Error:
```
Traceback (most recent call last):
  File "maml_examples/cluster_maml_trpo_ant.py", line 1, in <module>
    from sandbox.rocky.tf.algos.maml_trpo import MAMLTRPO
ImportError: No module named 'sandbox.rocky.tf.algos.maml_trpo'
```
I have installed rllab3 , and set `PYTHONPATH` properly.
then `source activate rllab3` , go to maml_rl directory and run `python maml_examples/cluster_maml_trpo_ant.py `, and this error occurs.
What's wrong? should I `git clone maml_rl` into some directory under rllab?

**Comment by dragen1860** [comment]
I should use the `rllab` in this git rep.

**Comment by MichalisLazarou** [comment]
I get the same error how did you solve it?
